### PR TITLE
rebrand: update screenshots

### PR DESCRIPTION
**Pull request by RoootTheFox**
Update the launcher screenshots on the website to use Prism Launcher 5.0 instead of PolyMC.
The instances are not exactly the same but I am sure they will get the job done just as well.
I also updated the screenshots that aren't used on the website anywhere, just to be sure.
MacOS and Windows screenshots aren't updated yet.

### CODE REVIEW

**Comment by RoootTheFox** [comment]
Thanks! I spent probably too much time getting the dimensions exactly right
Yours in #24 look good too!

**Comment by Lgmrszd** [comment]
I've used xdotool to set dimensions perfectly but kinda rushed last ones lmao

**Review by K3das — APPROVED** [review]
LGTM :)

**Comment by ZekeSmith** [comment]
I have chose #24 over this pr, thanks for your effort though.

**Pull request closed without merging**
