### PR TITLE
New screenshots

### PR DESCRIPTION
**Pull request by Lgmrszd**
New screenshot for the website.
(Doesn't contain Windows or Mac screenshots)
(Some of the screenshots are a bit off on the dimensions)
(Cat one wasn't updated since I couldn't find any usage of these screenshots)

### CODE REVIEW

**Review by K3das — APPROVED** [review]
LGTM :)

**Comment by TayouVR** [comment]
windows screenshots: (841x650, old were 802x632)
light
dark
feel free to add these

**Comment by Lgmrszd** [comment]
> windows screenshots
Your profile is exposed on those. You can hide it (without removing)

Otherwise feel free to submit separate PR I think that would be easier

**Comment by TayouVR** [comment]
> Also feel free to submit separate PR I think that would be easier

fair alright, will do

**Pull request merged**
